server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-service


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://linux1:7001/eureka   # ,http://linux2:7001/eureka

feign:
  hystrix:
    enabled: true

logging:
  level:
    com.czl.cloud.service.FeignPaymentService: debug

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000